export const CREATE_COMPANY = 'CREATE_COMPANY';
export const GET_MY_COMPANY = 'GET_MY_COMPANY';
export const GET_COMPANY_BY_ID = 'GET_COMPANY_BY_ID';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
