export const ADD_REMOVE_MY_FAVORITE_VACANCY = 'ADD_REMOVE_MY_FAVORITE_VACANCY';
export const ADD_REMOVE_MY_FAVORITE_RESUME = 'ADD_REMOVE_MY_FAVORITE_RESUME';
export const GET_MY_FAVORITE_RESUMES_IDS = 'GET_MY_FAVORITE_RESUMES_IDS';
export const RESPOND = 'RESPOND';
export const GET_RESPOND = 'GET_RESPOND';
export const GET_RESPONDS_BY_VACANCY_ID = 'GET_RESPONDS_BY_VACANCY_ID';
